//
//  CommonAPI.swift
//  VFantasyGlobal
//
//  Created by User on 25/05/2022.
//

import Foundation

struct CommonAPI {
    static let api_login = "/api/v1/login"
    static let api_register = "/api/v1/auth/register"
    static let api_social_login = "/api/v1/auth/social"
    static let api_list_news = "/api/v1/posts"
    static let api_open_leagues = "/api/v1/leagues/open_league"
    static let api_pending_leagues = "/api/v1/invitations/pending_list"
    static let api_my_leagues = "/api/v1/leagues/my_index"
    static let api_create_league = "/api/v1/leagues"
    static let api_forgot_password = "/api/v1/users/forgot"
    static let api_league_detail_information = "/api/v1/leagues"
    static let api_league_teams = "/api/v1/teams"
    static let api_league_friends = "/api/v1/invitations/search_friends"
    static let api_create_team = "/api/v1/teams"
    static let api_remove_team = "/api/v1/leagues/remove_team"
    static let api_invite_friend = "/api/v1/invitations"
    static let api_decision_invitation = "/api/v1/invitations/decision"
    static let api_get_budget_option = "/api/v1/leagues/get_form/%d"
    static let api_leave_league = "/api/v1/leagues/leave"
    static let api_stop_league = "/api/v1/leagues"
    static let api_upload_file = "/api/v1/upload"
    static let api_edit_league = "/api/v1/leagues"
    static let api_team_lineup = "/api/v1/teams/lineup/%d"
    static let api_player_list = "/api/v1/players"
    static let api_list_club = "/api/v1/real_clubs"
    static let api_add_player = "/api/v1/global/teams/%d/add_player"
    static let api_remove_player = "/api/v1/global/teams/%d/remove_player"
    static let api_join_league = "/api/v1/leagues/join"
    static let api_list_season = "/api/v1/seasons"
    static let api_edit_team = "/api/v1/teams/%d"
    static let api_team_detail = "/api/v1/teams/%d"
    static let api_team_statistic = "/api/v1/teams/%d/statistic"
    static let api_player_detail = "/api/v1/players/%d"
    static let api_team_pitch_view = "/api/v1/teams/%d/pitchview"
    static let api_player_statistic = "/api/v1/players/%d/statistic"
    static let api_player_statistic_with_team = "/api/v1/players/%d/team/%d/statistic"
    static let api_player_team_statistic = "/api/v1/players/%d/statistic"
    static let api_team_squad = "/api/v1/teams/%d/squad"
    static let api_logout = "/api/v1/logout"
    static let api_complete_lineup = "/api/v1/teams/%d/complete_lineup"
    static let api_global_complete_lineup = "/api/v1/global/teams/%d/complete_lineup"
    static let api_transfer_player_list = "/api/v1/teams/%d/transfer_player_list"
    static let api_change_formation = "/api/v1/teams/%d/change_formation"
    static let api_get_profile = "/api/v1/profile/%d"
    static let api_update_profile = "/api/v1/profile"
    static let api_start_league = "/api/v1/leagues/%d/start"
    static let api_transfer_record = "/api/v1/teams/%d/transfer_histories"
    static let api_transfer_player = "/api/v1/teams/%d/transfer_player"
    static let api_setting = "/api/v1/settings"
    static let api_changePassword = "/api/v1/change_password"
    static let api_my_match_results = "/api/v1/leagues/get_my_match_results"
    static let api_real_rounds = "/api/v1/real_matches"
    static let api_team_results = "/api/v1/leagues/%d/get_team_results"
    static let api_match_results = "/api/v1/leagues/%d/get_match_results"
    static let api_trade_request = "/api/v1/trade_requests"
    static let api_decision_trade_request = "/api/v1/trade_requests/%d/decision"
    static let api_register_notification = "/api/v1/update_device_of_user"
    static let api_pick_history = "/api/v1/leagues/%d/pick_histories"
    static let api_trade_request_results = "/api/v1/trade_requests/get_results"
    static let api_cancel_trade = "/api/v1/trade_requests/%d/cancel"
    static let api_notification_list = "/api/v1/notifications"
    static let api_join_draft = "/api/v1/leagues/%d/join_draft"
    static let api_end_countdown = "/api/v1/leagues/%d/end_countdown"
    static let api_end_turn = "/api/v1/teams/%d/end_turn"
    static let api_total_notification = "/api/v1/notifications/total"
    static let api_read_notification = "/api/v1/notifications/read"
    static let api_languages = "/api/v1/languages"
    static let api_max_round = "/api/v1/real_matches/max_round"
    static let api_latest_round = "/api/v1/real_rounds/latest"
    static let api_follow_play_day = "/api/v1/teams/follow_play_day"
    // Profile
    static let api_country = "/api/v1/countries"
    static let api_city = "/api/v1/cities"
    static let api_club = "/api/v1/clubs"
    // Global
    static let api_global_myteam = "/api/v1/global/teams/my-team"
    static let api_global_myteams = "/api/v1/global/teams/my-teams"
    static let api_global_createTeam = "/api/v1/global/teams"
    static let api_global_editTeam = "/api/v1/global/teams/%d"
    static let api_global_detailTeam = "/api/v1/global/teams/%d"
    static let api_global_squad = "/api/v1/global/teams/%d/squad"
    static let api_global_gameweek_list = "/api/v1/global/teams/%d/gameweek"
    static let api_global_all_gameweek = "/api/v1/global/gameweek"
    static let api_global_create_league = "/api/v1/global/leagues"
    static let api_global_update_league = "/api/v1/global/leagues/%d"
    static let api_global_transfer_player_list = "/api/v1/global/teams/%d/transfer_player_list"
    static let api_global_transfer_player = "/api/v1/global/teams/%d/transfer_player"
    static let api_global_league_friends = "/api/v1/global/invitations/search_friends"
    static let api_global_invite_friend = "/api/v1/global/invitations"
    static let api_global_my_league = "/api/v1/global/leagues/my_index"
    static let api_global_delete_league = "/api/v1/global/leagues/%d"
    static let api_global_ranking = "/api/v1/global/leagues/%d/ranking"
    static let api_global_leave_league = "/api/v1/global/leagues/%d/leave"
    static let api_global_statistic_team_points = "/api/v1/global/statistic/team_points"
    static let api_global_statistic_top_transfers_in = "/api/v1/global/statistic/top_transfers_in"
    static let api_global_statistic_top_transfers_out = "/api/v1/global/statistic/top_transfers_out"
    static let api_global_statistic_top_players_by_round = "/api/v1/global/statistic/top_players_by_round"
    static let api_global_statistic_most_valuable_teams = "/api/v1/global/statistic/most_valuable_teams"
    static let api_global_statistic_latest_injuries = "/api/v1/global/statistic/latest_injuries"
    static let api_global_players_stats = "/api/v1/global/players/stats"
    static let api_global_team_of_the_week = "/api/v1/teams/get_team_of_the_week"
    //Pitch
    static let api_global_pitchTeam = "/api/v1/global/teams/%d/pitchview"
    static let api_global_points = "/api/v1/global/teams/%d/points"
    static let api_global_pitchTeam_changeFormation = "/api/v1/global/teams/%d/change_formation"
    static let api_global_redeem_join_league = "/api/v1/global/leagues/join/%@"
    //League
    static let api_global_league_detail = "/api/v1/global/leagues/%d"
    static let api_h2h_real_rounds = "/api/v1/real_rounds/remaining"
    static let api_global_ranking_by_round = "/api/v1/global/leagues/%d/ranking/%d"
    
    //Walkthrough
    static let api_walk_through = "/api/v1/walkthroughs/first"
    // Transfer
    static let api_validate_transfer_deadline = "/api/v1/global/teams/%d/validate_transfer_deadline"
    // Home logo
    static let api_home_logo = "/api/v1/homepage/logo"
    
    //Auto pick
    static let api_auto_pick_players = "/api/v1/global/teams/%d/auto_pick_players"
    static let api_remove_auto_pick_players = "/api/v1/global/teams/%d/remove_auto_picked_players"
    
    //Super 7
    static let api_super7_myteam = "/api/v1/super7/teams/my-team"
    static let api_super7_createteam = "/api/v1/super7/teams"
    static let api_super7_editteam = "/api/v1/super7/teams/%d"
    static let api_super7_detailteam = "/api/v1/super7/teams/%d"
    static let api_super7_current_league = "/api/v1/super7/leagues/global"
    static let api_super7_pitchview = "/api/v1/super7/teams/%d/pitchview"
    static let api_super7_autopick = "/api/v1/super7/teams/%d/auto_pick_players"
    static let api_super7_all_gameweek = "/api/v1/super7/gameweek"
    static let api_super7_dream_teams = "/api/v1/super7/teams/dream_team"
    static let api_super7_claim_prize = "/api/v1/super7/teams/%d/claim_prize"
    static let api_super7_ranking = "/api/v1/super7/leagues/%d/ranking"

}
